name: Run API tests for Raiffeisen backend

on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 */6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run API tests
        run: |
          mvn test
